import { Metadata } from "next";
import "./global.css";
import ThemeProvider from "@/components/theme-provider";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial",
    template: "%s | Bantin",
  },

  description: "Generated by Next.js ",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <ThemeProvider>
      <body>
        <header className="sticky top-0  flex p-4 bg-black text-white">
          <p>Header</p>
        </header>
        {children}
        <footer className="fixed bottom-0 w-full flex p-4 bg-black text-white">
          <p>Footer</p>
        </footer>
      </body>
    </ThemeProvider>
  </html>
);

export default RootLayout;
